KUSYS-Demo/Models/Student.cs
using System.ComponentModel.DataAnnotations;

namespace KUSYS_Demo.Models
{
    public class Student
    {

        public int StudentId { get; set; }
        public DateTime BirthDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public IEnumerable<StudentCourse> StudentCourses { get; set; }
    }
}

KUSYS-Demo/Models/StudentCourse.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KUSYS_Demo.Models
{
    public class StudentCourse
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey(nameof(Course))]
        public string CourseId { get; set; }
        public Course Course { get; set; }

        [ForeignKey(nameof(Student))]
        public int StudentId { get; set; }
        public Student Student { get; set; }
    }
}

KUSYS-Demo/Pages/Courses/list.cshtml.cs
using KUSYS_Demo.DataContext;
using KUSYS_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace KUSYS_Demo.Pages.Courses
{
    public class listModel : PageModel
    {
        private readonly AplicationDbContext aplicationDbContext;

        
        public listModel(AplicationDbContext aplicationDbContext)
        {
            this.aplicationDbContext = aplicationDbContext;
        }
        public List<Course> Courses { get; set; }
        public List<Student> students { get; set; }
        public List<StudentCourse> StudentCourses { get; set; }

        public void OnGet()
        {
            Courses=aplicationDbContext.Courses.ToList();
            students=aplicationDbContext.Students.ToList();
            //StudentCourses=aplicationDbContext.StudentCourses.ToList();  
        }
    }
}

KUSYS-Demo/Pages/Students/Add.cshtml.cs
using KUSYS_Demo.DataContext;
using KUSYS_Demo.Models.ViewModels;
using KUSYS_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KUSYS_Demo.Pages.Students
{
    public class AddModel : PageModel
    {
        private readonly AplicationDbContext addStudentContext;

        [BindProperty]
        public AddStudent AddStudentRequest { get; set; }

        public AddModel(AplicationDbContext aplicationDbContext)
        {
            this.addStudentContext = aplicationDbContext;
        }

        public void OnGet()
        {
        }
        public async Task<IActionResult>  OnPost()
        {
            var student = new Student()
            {
                
                FirstName = AddStudentRequest.FirstName,
                LastName = AddStudentRequest.LastName,
                BirthDate = AddStudentRequest.BirthDate,
            };

          await  addStudentContext.Students.AddAsync(student);
          await  addStudentContext.SaveChangesAsync();
            return RedirectToPage("/Students/List");

        }
    }
}

KUSYS-Demo/Pages/Students/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KUSYS_Demo.Pages.Students
{
    public class DetailsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

KUSYS-Demo/Pages/Students/Edit.cshtml.cs
using KUSYS_Demo.DataContext;
using KUSYS_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace KUSYS_Demo.Pages.Students
{

    public class EditModel : PageModel
    {
        [BindProperty]
        public Student Student { get; set; }

        [BindProperty]
        public Course Course { get; set; }

        private readonly AplicationDbContext aplicationDbContext;
            
        public EditModel( AplicationDbContext aplicationDbContext)
        {
            this.aplicationDbContext = aplicationDbContext;
        }

        public List<Course> Courses { get; set; }

        public async Task OnGet(int StudentId)
        {
          Student = await aplicationDbContext.Students.FindAsync(StudentId);
          //Courses = await aplicationDbContext.Courses.Include(c => c.StudentId == StudentId).ToListAsync();        
        
        }
        public async Task<IActionResult> OnPostEdit() 
        {
            var existingStudent =await aplicationDbContext.Students.FindAsync(Student.StudentId);
            
            if (existingStudent != null) 
            {
                existingStudent.FirstName = Student.FirstName;   
                existingStudent.LastName = Student.LastName;
                existingStudent.BirthDate = Student.BirthDate;
            }
          await  aplicationDbContext.SaveChangesAsync();
            return RedirectToPage("/Students/List");
        }
        public async Task<IActionResult> OnPostDelete() 
        {
            var existingStudent= await aplicationDbContext.Students.FindAsync(Student.StudentId);
            if (existingStudent != null) 
            {
            aplicationDbContext.Students.Remove(existingStudent);
               await aplicationDbContext.SaveChangesAsync(true);
                return RedirectToPage("/Students/List");
            }
            return Page();
        }
    }
}

KUSYS-Demo/Pages/Students/EditCourses.cshtml.cs
using KUSYS_Demo.DataContext;
using KUSYS_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KUSYS_Demo.Pages.Students
{
    public class EditCoursesModel : PageModel
    {
        [BindProperty]
        public Student Student { get; set; }

        [BindProperty]
        public Course Course { get; set; }

        private readonly AplicationDbContext aplicationDbContext;

        public EditCoursesModel(AplicationDbContext aplicationDbContext)
        {
            this.aplicationDbContext = aplicationDbContext;
        }

        public List<Course> Courses { get; set; }

        public async Task OnGet(int StudentId)
        {
            Student = await aplicationDbContext.Students.FindAsync(StudentId);
            //Courses = await aplicationDbContext.Courses.Include(c => c.StudentId == StudentId).ToListAsync();        

        }
        public async Task<IActionResult> OnPostEdit()
        {
            var existingStudent = await aplicationDbContext.Students.FindAsync(Student.StudentId);

            if (existingStudent != null)
            {
                existingStudent.FirstName = Student.FirstName;
                existingStudent.LastName = Student.LastName;
                existingStudent.BirthDate = Student.BirthDate;
            }
            await aplicationDbContext.SaveChangesAsync();
            return RedirectToPage("/Students/List");
        }
        public async Task<IActionResult> OnPostDelete()
        {
            var existingStudent = await aplicationDbContext.Students.FindAsync(Student.StudentId);
            if (existingStudent != null)
            {
                aplicationDbContext.Students.Remove(existingStudent);
                await aplicationDbContext.SaveChangesAsync(true);
                return RedirectToPage("/Students/List");
            }
            return Page();
        }
    }
}

KUSYS-Demo/Pages/Students/List.cshtml.cs
using KUSYS_Demo.DataContext;
using KUSYS_Demo.Models;
using KUSYS_Demo.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace KUSYS_Demo.Pages.Students
{
    public class ListModel : PageModel
    {
       

        private readonly AplicationDbContext aplicationDbContext;

        public ListModel(AplicationDbContext aplicationDbContext)
        {
            this.aplicationDbContext = aplicationDbContext;     
        }
       public List<Student> students { get; set; }
       
      
        public async Task OnGet() 
        {
            students =await aplicationDbContext.Students.ToListAsync();
        }
      
    }
}

KUSYS-Demo/Pages/Students/StudentCourse.cshtml.cs
using KUSYS_Demo.DataContext;
using KUSYS_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;

namespace KUSYS_Demo.Pages.Students
{
    public class StudentCourseModel : PageModel
    {
       
        private readonly AplicationDbContext aplicationDbContext;

        public StudentCourseModel(AplicationDbContext aplicationDbContext)
        {
            this.aplicationDbContext = aplicationDbContext;
        }
        public List<Student> students { get; set; }
        public async Task OnGet()
        {
            students = await aplicationDbContext.Students.ToListAsync();
        }

       


    }
}

KUSYS-Demo/Pages/Students/Add.cshtml
@page
@model KUSYS_Demo.Pages.Students.AddModel
@{
    <title> Students</title>
}



<div class="bg-secondary bg-opacity-10 py-2 mb-4">
    <div class="container">
        <h1>ADDING  AND LISTING STUDENTS</h1>   
    </div>
    </div>
   <div>
    <div class="container">
        <form method="post">
        <div class="mb-3">
            <b><label for="FName">First Name :</label></b>
            <input type="text" id="FName" class="form-control" name="FirstName" asp-for="AddStudentRequest.FirstName" /><br />
        </div>
        <div class="mb-3">
            <b>  <label for="LName" class="form-label">Last Name :</label></b>
            <input type="text" id="LName"  class="form-control" name="LastName" asp-for="AddStudentRequest.LastName" /><br />
        </div>
        <div class="mb-3">
            <b> <label for="BDate" class="form-label">Birth Date  :</label></b>
            <input type="date" id="BDate" class="form-control" name="BirthDate" asp-for="AddStudentRequest.BirthDate" /><br />
        </div>
        <div class="mb-3">
            <center>
                 
        <button type="submit" class="btn btn-primary">Save</button>
        <strong> <a class="nav-link" asp-area="" asp-page="/Students/List">List Students</a></strong>
                   
       
                </center>
        </div>
        </form>
    </div>
</div>
  

KUSYS-Demo/Pages/Students/Details.cshtml
@page "{StudentId:int}"
@model KUSYS_Demo.Pages.Students.DetailsModel
@{
}
@*<table cellpadding="0" cellspacing="0" border="0">
    <tr>
        <td valign="top"><b>@Html.DisplayNameFor(model => model.Address):</b></td>
        <td>
            @Html.DisplayFor(model => model.Address)
            <br />
            @Html.DisplayFor(model => model.City),
            @Html.DisplayFor(model => model.PostalCode)
            <br />
            @Html.DisplayFor(model => model.Country)
        </td>
    </tr>
</table>*@

KUSYS-Demo/Pages/Students/Edit.cshtml
@page "{StudentId:int}"
@model KUSYS_Demo.Pages.Students.EditModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-4">
    <div class="container">
        <h1>STUDENT INFORMATION</h1>
    </div>
</div>

@if(Model.Student != null)
{
   <div>
    <div class="container">
        <form method="post">
         
            <div class="mb-3">
                <b><label for="FName">First Name :</label></b>
                <input type="text" id="FName" class="form-control" name="FirstName" asp-for="Student.FirstName" /><br />
            </div>
            <div class="mb-3">
                <b>  <label for="LName" class="form-label">Last Name :</label></b>
                <input type="text" id="LName" class="form-control" name="LastName" asp-for="Student.LastName" /><br />
            </div>
            <div class="mb-3">
                <b> <label for="BDate" class="form-label">Birth Date  :</label></b>
                <input type="date" id="BDate" class="form-control" name="BirthDate" asp-for="Student.BirthDate" /><br />
            </div>
            <div class="mb-3">
                <center>

                    <button type="submit" class="btn btn-primary" asp-page-handler="Edit">Save</button>
                 <button type="submit" class="btn btn-danger" asp-page-handler="Delete">Delete</button>
                </center>
            </div>
          </form>
       
    </div>
    </div>
}
else
{
    <div class="container">
        <p>Sayfa Bulunamadı!</p>
    </div>
}

KUSYS-Demo/Pages/Students/EditCourses.cshtml
@page "{StudentId:int}"
@model KUSYS_Demo.Pages.Students.EditCoursesModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-4">
    <div class="container">
        <h1>STUDENT INFORMATION</h1>
    </div>
</div>

@if (Model.Student != null)
{
    <div>
        <div class="container">
            <form method="post">

                <div class="mb-3">
                    <b><label for="FName">First Name :</label></b>
                    <input type="text" id="FName" class="form-control" name="FirstName" asp-for="Student.FirstName" /><br />
                </div>
                <div class="mb-3">
                    <b>  <label for="LName" class="form-label">Last Name :</label></b>
                    <input type="text" id="LName" class="form-control" name="LastName" asp-for="Student.LastName" /><br />
                </div>
            
                <div class="mb-3">
                    <center>

                        <button type="submit" class="btn btn-primary" asp-page-handler="Edit">Save</button>
                        <button type="submit" class="btn btn-danger" asp-page-handler="Delete">Delete</button>
                    </center>
                </div>
            </form>

        </div>
    </div>
}
else
{
    <div class="container">
        <p>Sayfa Bulunamadı!</p>
    </div>
}

KUSYS-Demo/Pages/Students/List.cshtml
@page
@model KUSYS_Demo.Pages.Students.ListModel
@{
    <title>List Student</title>
}
<div class="bg-secondary bg-opacity-10 py-2 mb-4">
    <div class="container">
        <h1>LISTING STUDENTS</h1>
    </div>
</div>

@if (Model.students != null && Model.students.Any())
{
    <div class="container">
    <table class="table">
        <thead>
            <tr>
               
                <td>FirstName</td>
                <td>LastName</td>
                <td>BirtDate</td>
                <td>Update</td>
           
            </tr>
        </thead>
        <tbody>
            @foreach (var student in Model.students)
            {
                <tr>
                    
                    <td>@student.FirstName</td>
                    <td>@student.LastName</td>
                    <td>@student.BirthDate.ToShortDateString()</td>
                    <td><a href="/Students/Edit/@student.StudentId">Update</a></td>
                  
                </tr>
            }       
        </tbody>
    </table>

</div>
}else
{
        <div class="container">
            <p>Sayfa Bulunamadı öğrenci ekleyin!</p>
        </div>
}

KUSYS-Demo/Pages/Students/StudentCourse.cshtml
@page 
@model KUSYS_Demo.Pages.Students.StudentCourseModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-4">
    <div class="container">
        <h1>LISTING STUDENTS</h1>
    </div>
</div>

@if (Model.students != null && Model.students.Any())
{
    <div class="container">
        <table class="table">
            <thead>
                <tr>

                    <td>FirstName</td>
                    <td>LastName</td>
                    <td>Detail</td>

                </tr>
            </thead>
            <tbody>
                @foreach (var student in Model.students)
                {
                    <tr>

                        <td>@student.FirstName</td>
                        <td>@student.LastName</td>
                       <td><a href="/Students/Details/@student.StudentId">Details</a></td>
                        @*<td><button class="btn btn-sm btn-dark details" data-id="@student.StudentId">Details</button></td>*@

                    </tr>
                }
            </tbody>
        </table>

    </div>
    <div class="modal fade" tabindex="-1" role="dialog" id="ModalCourse">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Product Details</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body"></div>
            </div>
        </div>
    </div>
    @section scripts{
    <script>
        $(function () {
            $('button.details').on('click', function () {
                $('.modal-body').load(`/Detail/product?id=${$(this).data('StudentId')}`);
            });
        })
    </script>
}
}


else
{
    <div class="container">
        <p>Page Not Found Add Student!</p>
    </div>
}